CACHE_DIR = '/home/chansingh/mntv1/mprompt/cache'
# RESULTS_DIR = '/home/chansingh/mprompt/results/'
RESULTS_DIR = '/home/chansingh/mntv1/mprompt/'
REPO_DIR = '/home/chansingh/mprompt/'
SAVE_DIR_FMRI = '/home/chansingh/mntv1/fmri/'