CACHE_DIR = '/accounts/campus/aliyahhsu/m_cache'
# RESULTS_DIR = '/home/chansingh/mprompt/results/'
RESULTS_DIR = '/accounts/campus/aliyahhsu/module-prompt/results'
REPO_DIR = '/accounts/campus/aliyahhsu/module-prompt'
SAVE_DIR_FMRI = '/home/chansingh/mntv1/fmri/'